# Generated by Django 3.2.4 on 2021-07-29 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DropLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_long', models.FloatField()),
                ('drop_lat', models.FloatField()),
                ('drop_locname', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_title', models.CharField(max_length=200, verbose_name=' Title ')),
                ('drop_category', models.CharField(choices=[('0', 'Animation'), ('1', 'ART'), ('2', 'Video'), ('3', 'NFT'), ('4', 'Image'), ('5', 'Links')], default='0', max_length=60, verbose_name=' Category ')),
                ('drop_type', models.CharField(choices=[('WEB', 'Website'), ('YT', 'Youtube Video'), ('IMG', 'Photo'), ('ANI', 'Animation'), ('AUD', 'Audio')], default='WEB', max_length=30, verbose_name=' Type of drop ')),
                ('drop_description', models.TextField(verbose_name=' Add Description ')),
                ('drop_url', models.URLField(blank=True, null=True, verbose_name=' Paste your link here ')),
                ('drop_asset', models.CharField(default='asset_1', max_length=200, verbose_name=' Choose your asset ')),
                ('drop_loc', models.ManyToManyField(null=True, to='api_app.DropLocation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
