# Generated by Django 3.2.4 on 2021-08-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='drop_type',
        ),
        migrations.AddField(
            model_name='drop',
            name='drop_file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='droplocation',
            name='drop_locname',
            field=models.CharField(default=' ', max_length=2000),
        ),
    ]
